// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace projekt.Migrations
{
    [DbContext(typeof(DatabaseDbContext))]
    partial class DatabaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projekt.Data.Models.Czat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("UzytkownikId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Czaty");
                });

            modelBuilder.Entity("projekt.Data.Models.Konto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Haslo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypKonta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UzytkownikId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId")
                        .IsUnique();

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("projekt.Data.Models.Obserwacja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OgloszenieId")
                        .HasColumnType("bigint");

                    b.Property<long>("UzytkownikId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OgloszenieId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Obserwacje");
                });

            modelBuilder.Entity("projekt.Data.Models.Ogloszenie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AutorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataStworzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWygasniecia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Ogloszenia");
                });

            modelBuilder.Entity("projekt.Data.Models.Uzytkownik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("projekt.Data.Models.Wiadomosc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AutorId")
                        .HasColumnType("bigint");

                    b.Property<long>("CzatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tekst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CzatId");

                    b.ToTable("Wiadomosci");
                });

            modelBuilder.Entity("projekt.Data.Models.Czat", b =>
                {
                    b.HasOne("projekt.Data.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Czat")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("projekt.Data.Models.Konto", b =>
                {
                    b.HasOne("projekt.Data.Models.Uzytkownik", "Uzytkownik")
                        .WithOne("Konto")
                        .HasForeignKey("projekt.Data.Models.Konto", "UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("projekt.Data.Models.Obserwacja", b =>
                {
                    b.HasOne("projekt.Data.Models.Ogloszenie", "Ogloszenie")
                        .WithMany("Obserwacje")
                        .HasForeignKey("OgloszenieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("projekt.Data.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Obserwacje")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogloszenie");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("projekt.Data.Models.Ogloszenie", b =>
                {
                    b.HasOne("projekt.Data.Models.Uzytkownik", "Autor")
                        .WithMany("Ogloszenia")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("projekt.Data.Models.Wiadomosc", b =>
                {
                    b.HasOne("projekt.Data.Models.Uzytkownik", "Autor")
                        .WithMany("Wiadomosci")
                        .HasForeignKey("AutorId");

                    b.HasOne("projekt.Data.Models.Czat", "Czat")
                        .WithMany("Wiadomosci")
                        .HasForeignKey("CzatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Czat");
                });

            modelBuilder.Entity("projekt.Data.Models.Czat", b =>
                {
                    b.Navigation("Wiadomosci");
                });

            modelBuilder.Entity("projekt.Data.Models.Ogloszenie", b =>
                {
                    b.Navigation("Obserwacje");
                });

            modelBuilder.Entity("projekt.Data.Models.Uzytkownik", b =>
                {
                    b.Navigation("Czat");

                    b.Navigation("Konto");

                    b.Navigation("Obserwacje");

                    b.Navigation("Ogloszenia");

                    b.Navigation("Wiadomosci");
                });
#pragma warning restore 612, 618
        }
    }
}
